---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
**Fact 3** 
<br /> $i \in [m;n]$
<br /> $m \le n$
<br /> $N_{i}$=?
<br /> n-(m-1)=n-m+1

```{r}
count <- function(m, n){
print((m+1):(n-1))
}
length(count(-10,90))
```

**Fact 1**
<br /> m=1
<br /> n>0
<br /> $i \in [1;n]$
<br /> $N_{i}$=?
<br /> $N_{i}$=n

```{r}
count <- function(m, n){
length(m:n)
}
count(1,924310)
``` 

Think of an integer i with:
$i \in [1;10]$
```{r}
sample(x=c(1:10),             #integers to choose from
       size=1                 #the number of integers to choose
       )
```
Install package sets:
```{r}
install.packages('sets')
library('sets')
```


$i \in [-7;9]$
<br /> $N_{i}$=?
```{r}
odd_seq = seq(-7,9,by=2)
odd_seq
length(odd_seq)
```


```{r}
evens <- function(x){
  subset(x,             #object to be subsetted
         x %% 2 == 0)   #logical expression indicating elements or rows to keep: missing values are taken as false.
}
evens(8:10)
count <-evens(8:10)
length(count)
```

Calculate floor of integer(positive and negative):
```{r}
floor(3.14159265)
```

Calculate ceiling of integer(positive and negative):
```{r}
ceiling(50.5)
```
<br /> $i \in [1;2n]$
<br /> $N_{i}$=?
<br /> $N_{i}$=n/2

```{r}
evens <- function(x){
  subset(x,             #object to be subsetted
         x %% 2 == 0)   #logical expression indicating elements or rows to keep: missing values are taken as false.
}
evens(1:10)
count <-evens(1:10)
length(count)
```

**Fact 4** 
<br />k>0
<br />n>0
<br /> $i \in [1;kn]$
<br /> $N_{i}$=?
<br /> $N_{i}$=n/k
```{r}
multiples <- function(x){
  subset(x,             #object to be subsetted
         x %% 3 == 0)   #logical expression indicating elements or rows to keep: missing values are taken as false.
}
multiples(1:10)
count <-multiples(1:10)
length(count)
```
**Theorem 1**
<br />m>0
<br /> $m \le n$
<br /> $i \in [m;kn]$
<br /> $N_{i}$=?
<br /> $N_{i}$=(n-m+1)/k
m=4
k=5
n=100
<br /> $N_{i}$=(100-4+1)/5=19.4 
```{r}
multiples <- function(x){
  subset(x,             #object to be subsetted
         x %% 5 == 0)   #logical expression indicating elements or rows to keep: missing values are taken as false.
}
multiples(4:100)
count <-multiples(4:100)
length(count)
```
<br /> $\lfloor 4+100.5 \rfloor$
```{r}
floor(4+100.5)
```
```{r}
install.packages('primes')
```
```{r}
library(primes)
```

```{r}
generate_primes(1,10)
count<-generate_primes(1,10)
length(count)
```

```{r}
count <- function(m, n){
generate_primes(m,n)
}
count(1,10)
```

```{r}
count <- function(m,n){
  newlist <- generate_primes(m,n)
  length(newlist)
}
count(1,10)
```


```{r}
count <- function(m,n){
  newlist <- generate_primes(m,n)
  length(newlist)
}
count(1,10)
```

```{r}
count <- function(m,n){
  generate_primes(m,n)
  newlist <-generate_primes(m,n)
  print(newlist)
}
length(count(1,10))
```



**Prime Number Theorem**
```{r}
count <- function(m,n){
  generate_primes(m,n)
  newlist <-generate_primes(m,n)
  print(newlist)
}
length(count(1,2^4))
```